webSwagger/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace webSwagger.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

webSwagger/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using webSwagger.Areas.HelpPage.Models;

namespace webSwagger.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

webSwagger/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webSwagger.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            return View();
        }
        public ActionResult ValidateCode()
        {
            return View();
        }
    }
}

webSwagger/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using webSwagger.Base;
using webSwagger.JYAPI;

namespace webSwagger.Controllers
{
    [RoutePrefix("api/test")]
    public class ValuesController : BaseApiController
    {
        /// <summary>
        /// 产生验证码
        /// </summary>
        /// <returns></returns>
        [Route("GenerateCode")]
        public ApiResponse GenerateCode()
        {
            Context.Response.ContentType = "application/json";
            GeetestLib geetest = new GeetestLib(GeetestConfig.publicKey, GeetestConfig.privateKey);
            string appKey = System.Guid.NewGuid().ToString();
            Byte gtServerStatus = geetest.preProcess(appKey);
            Context.Session[GeetestLib.gtServerStatusSessionKey] = gtServerStatus;
            Context.Session["sessionID"] = appKey;
            return ResponseHelper.CreateApiResponse(10000,"success",geetest.getResponseStr());
        }
        [Route("ValidCode")]
        public ApiResponse Success()
        {
            GeetestLib geetest = new GeetestLib(GeetestConfig.publicKey, GeetestConfig.privateKey);
            Byte gt_server_status_code = (Byte)Context.Session[GeetestLib.gtServerStatusSessionKey];
            String userID = (String)Context.Session["sessionID"];
            int result = 0;
            String challenge = Context.Request.Form.Get(GeetestLib.fnGeetestChallenge);
            String validate = Context.Request.Form.Get(GeetestLib.fnGeetestValidate);
            String seccode = Context.Request.Form.Get(GeetestLib.fnGeetestSeccode);
            if (gt_server_status_code == 1)
                result = geetest.enhencedValidateRequest(challenge, validate, seccode, userID);
            else
                result = geetest.failbackValidateRequest(challenge, validate, seccode);
            if (result == 1)
                return ResponseHelper.CreateApiResponse(10000,"验证码校验成功");
            else 
                return ResponseHelper.CreateApiResponse(10001,"验证码校验失败");

        }

    }
}

webSwagger/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

webSwagger/Views/Home/ValidateCode.cshtml
@{
    ViewBag.Title = "ValidateCode";
}

<h2>极验API_____Demo</h2>
<div class="row">
    <div id="captcha"></div>
    <div class="row">
        @*<asp:Button ID="submitBtn" runat="server" OnClick="submitBtn_Click" Text="登　录" />*@
        <input type="button" id="submit" value="提交" v-on:click="xxx" />
    </div>
    <script src="http://static.geetest.com/static/tools/gt.js"></script>
    @section Script{
        <script>
            var handler = function (captchaObj) {
                // 将验证码加到id为captcha的元素里
                captchaObj.appendTo("#captcha");
            };
            $.ajax({
                // 获取id，challenge，success（是否启用failback）
                url: "/api/test/GenerateCode",
                type: "post",
                dataType: "json", // 使用jsonp格式
                success: function (data) {
                    console.log(data);
                    // 使用initGeetest接口
                    // 参数1：配置参数，与创建Geetest实例时接受的参数一致
                    // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
                    if (data.Result == 10000) {
                        var data = JSON.parse( data.Data);
                        initGeetest({
                            gt: data.gt,
                            challenge: data.challenge,
                            product: "embed", // 产品形式
                            offline: !data.success
                        }, handler);
                    }
                    else
                    {
                        alert("验证码初始化失败");
                    }
                }
            });

            new Vue({
                el: '.row',
                methods: {
                    xxx: function () {
                        $.ajax({
                            url: '/api/test/ValidCode',
                            type: 'post',
                            dataType: 'json',
                            success: function (data) {
                                if (data.Result == 10000) {
                                    alert("Success");
                                }
                            },
                            error: function (data) {
                            }
                        })
                    }
                }
            });
        </script>
    }
</div>

webSwagger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/vue.min.js"></script>
    <script src="~/Scripts/vue-resource.min.js"></script>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("极验验证码", "ValidateCode", "Home", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>
    @RenderSection("Script", false)
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>